### ISSUE TITLE
Add `command` from Link File to Luigi file argument list.

### ISSUE THREAD

**Issue by jakereps** [acgt-tax-consultants/orchard#41]
Currently the generator outputs

```python
class ModuleOne(ExternalProgramTask):
    def program_args(self):
        return ['./ModuleOne', 'a', 'b', 'c']
```

Where `b` is `outfile` and `c` is `digit`. In the link file these have commands

```yaml
- name: ModuleOne
  arguments:
  - name: infile
  - name: outfile
    command: --out
    isBranch: false
  - name: digit
    command: -d
```

The luigi file should output anything that has a command with the command before it like:

```python
class ModuleOne(ExternalProgramTask):
    def program_args(self):
        return ['./ModuleOne', 'a', '--out', 'b', '-d', 'c']
```
